=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/schema/shortcut.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://hotkys.com/schema/shortcut.schema.json",
  "title": "Application shortcuts",
  "description": "A product in the catalog",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "Schema reference",
      "type": "string",
      "const": "schema/shortcut.schema.json"
    },
    "bundleId": {
      "description": "Bundle id is a unique identifier for the macOS application. Example: 'com.microsoft.VSCode'",
      "type": "string",
      "minLength": 1
    },
    "hostname": {
      "description": "Hostname of the web application. Example: 'code.visualstudio.com'",
      "type": "string",
      "minLength": 1
    },
    "slug": {
      "description": "Unique readable identifier",
      "type": "string",
      "minLength": 1,
      "pattern": "^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$"
    },
    "name": {
      "description": "Name of the application",
      "type": "string",
      "minLength": 1
    },
    "source": {
      "description": "Link to the source of the shortcuts",
      "type": "string",
      "format": "uri"
    },
    "keymaps": {
      "description": "List of the application keymaps. Most of the applications have single keymap that should be named 'Default'.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/keymap"
      },
      "minItems": 1
    }
  },
  "required": ["$schema", "name", "slug", "keymaps"],
  "additionalProperties": false,
  "$defs": {
    "keymap": {
      "description": "Application keymap. Keymap is a shortcut configuration.",
      "type": "object",
      "properties": {
        "title": {
          "description": "Keymap title",
          "type": "string",
          "minLength": 1
        },
        "sections": {
          "description": "List of sections",
          "type": "array",
          "items": {
            "$ref": "#/$defs/section"
          },
          "minItems": 1
        }
      },
      "required": ["title", "sections"],
      "additionalProperties": false
    },
    "section": {
      "description": "Section with shortcuts or category. Examples: Edit, Navigate, Format.",
      "type": "object",
      "properties": {
        "title": {
          "description": "Section title",
          "type": "string",
          "minLength": 1
        },
        "shortcuts": {
          "description": "List of shortcuts",
          "type": "array",
          "items": {
            "$ref": "#/$defs/section-shortcut"
          },
          "minItems": 1
        }
      },
      "required": ["title", "shortcuts"],
      "additionalProperties": false
    },
    "section-shortcut": {
      "description": "Shortcut with title and key",
      "type": "object",
      "properties": {
        "title": {
          "description": "Shortcut title",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "key": {
          "description": "Shortcut key definition. Key consist of modifiers plus base key separated by '+' sign. Supported modifiers: 'ctrl', 'shift', 'opt', 'cmd'. Modifiers should be specified in that exact order, lowercase. Final shortcut token should always be a base key. Examples: 'ctrl+s', 'shift+cmd+e'. Shortcut macro or sequences of shortcuts are also supported and should be separated by whitespace (' '). Example: 'cmd+k cmd+s'",
          "type": "string",
          "minLength": 1
        },
        "comment": {
          "description": "Text comment for the shortcut. Can be used as a substitute or addition to the declared key",
          "type": "string",
          "maxLength": 50
        }
      },
      "required": ["title"],
      "anyOf": [
        {
          "required": [
            "key"
          ]
        },
        {
          "required": [
            "comment"
          ]
        }
      ],
      "additionalProperties": false
    }
  }
}

=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/typora.json
{
  "$schema": "schema/shortcut.schema.json",
  "bundleId": "abnerworks.Typora",
  "name": "Typora",
  "slug": "typora",
  "source": "https://support.typora.io/Shortcut-Keys/",
  "keymaps": [
    {
      "title": "Normal",
      "sections": [
        {
          "title": "File",
          "shortcuts": [
            {
              "title": "New",
              "key": "cmd+N"
            },
            {
              "title": "New Window",
              "key": "cmd+shift+N"
            },
            {
              "title": "New tab",
              "key": "cmd+T"
            },
            {
              "title": "Open",
              "key": "cmd+O"
            },
            {
              "title": "Open Quickly",
              "key": "cmd+shift+O"
            },
            {
              "title": "Reopen Closed File",
              "key": "cmd+shift+T"
            },
            {
              "title": "Save",
              "key": "cmd+S"
            },
            {
              "title": "Save As Duplicate",
              "key": "cmd+shift+S"
            },
            {
              "title": "Preference",
              "key": "cmd+,"
            },
            {
              "title": "Close",
              "key": "cmd+W"
            }
          ]
        },
        {
          "title": "Edit",
          "shortcuts": [
            {
              "title": "New Paragraph",
              "key": "enter"
            },
            {
              "title": "New Line",
              "key": "shift+enter"
            },
            {
              "title": "Cut",
              "key": "cmd+X"
            },
            {
              "title": "Copy",
              "key": "cmd+C"
            },
            {
              "title": "Paste",
              "key": "cmd+V"
            },
            {
              "title": "Copy As Markdown",
              "key": "cmd+shift+C"
            },
            {
              "title": "Paste As Plain Text",
              "key": "cmd+shift+V"
            },
            {
              "title": "Select All",
              "key": "cmd+A"
            },
            {
              "title": "Select Line/Sentence Select Row (in table)",
              "key": "cmd+L"
            },
            {
              "title": "Delete Row (in table)",
              "key": "cmd+shift+backspace"
            },
            {
              "title": "Select Style Scope Select Cell (in table)",
              "key": "cmd+E"
            },
            {
              "title": "Select Word",
              "key": "cmd+D"
            },
            {
              "title": "Delete Word",
              "key": "cmd+shift+D"
            },
            {
              "title": "Jump to Top",
              "key": "cmd+up"
            },
            {
              "title": "Jump to Selection",
              "key": "cmd+J"
            },
            {
              "title": "Jump to Bottom",
              "key": "cmd+down"
            },
            {
              "title": "Find",
              "key": "cmd+F"
            },
            {
              "title": "Find Next",
              "key": "cmd+G"
            },
            {
              "title": "Find Next",
              "key": "enter"
            },
            {
              "title": "Find Previous",
              "key": "cmd+shift+G"
            },
            {
              "title": "Find Previous",
              "key": "shift+enter"
            },
            {
              "title": "Replace",
              "key": "cmd+H"
            }
          ]
        },
        {
          "title": "Paragraph",
          "shortcuts": [
            {
              "title": "Heading 1",
              "key": "cmd+1"
            },
            {
              "title": "Heading 2",
              "key": "cmd+2"
            },
            {
              "title": "Heading 3",
              "key": "cmd+3"
            },
            {
              "title": "Heading 4",
              "key": "cmd+4"
            },
            {
              "title": "Heading 5",
              "key": "cmd+5"
            },
            {
              "title": "Heading 6",
              "key": "cmd+6"
            },
            {
              "title": "Heading 7",
              "key": "cmd+7"
            },
            {
              "title": "Paragraph",
              "key": "cmd+0"
            },
            {
              "title": "Increase Heading Level",
              "key": "cmd+="
            },
            {
              "title": "Decrease Heading Level",
              "key": "cmd+hyphen"
            },
            {
              "title": "Insert Table",
              "key": "cmd+opt+T"
            },
            {
              "title": "Code Fences",
              "key": "cmd+opt+C"
            },
            {
              "title": "Math Block",
              "key": "cmd+opt+B"
            },
            {
              "title": "Quote",
              "key": "cmd+opt+Q"
            },
            {
              "title": "Ordered List",
              "key": "cmd+opt+O"
            },
            {
              "title": "Unordered List",
              "key": "cmd+opt+U"
            },
            {
              "title": "Indent",
              "key": "cmd+["
            },
            {
              "title": "Indent",
              "key": "tab"
            },
            {
              "title": "Outdent",
              "key": "cmd+]"
            },
            {
              "title": "Outdent",
              "key": "shift+tab"
            }
          ]
        },
        {
          "title": "Format",
          "shortcuts": [
            {
              "title": "Strong",
              "key": "cmd+B"
            },
            {
              "title": "Emphasis",
              "key": "cmd+I"
            },
            {
              "title": "Underline",
              "key": "cmd+U"
            },
            {
              "title": "Code",
              "key": "cmd+shift+`"
            },
            {
              "title": "Strike",
              "key": "ctrl+shift+`"
            },
            {
              "title": "Hyperlink",
              "key": "cmd+K"
            },
            {
              "title": "Image",
              "key": "cmd+ctrl+I"
            },
            {
              "title": "Clear Format",
              "key": "cmd+\\"
            }
          ]
        },
        {
          "title": "View",
          "shortcuts": [
            {
              "title": "Toggle Sidebar",
              "key": "cmd+shift+L"
            },
            {
              "title": "Outline",
              "key": "cmd+ctrl+1"
            },
            {
              "title": "Articles",
              "key": "cmd+ctrl+2"
            },
            {
              "title": "File Tree",
              "key": "cmd+ctrl+3"
            },
            {
              "title": "Source Code Mode",
              "key": "cmd+/"
            },
            {
              "title": "Focus Mode",
              "key": "F8"
            },
            {
              "title": "Typewriter Mode",
              "key": "F9"
            },
            {
              "title": "Toggle Fullscreen",
              "key": "cmd+opt+F"
            },
            {
              "title": "Switch Between Opened Documents",
              "key": "cmd+`"
            }
          ]
        }
      ]
    }
  ]
}

=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/vsCode.json
{
  "$schema": "schema/shortcut.schema.json",
  "bundleId": "com.microsoft.VSCode",
  "name": "Visual Studio Code",
  "slug": "vsCode",
  "keymaps": [
    {
      "title": "Default",
      "sections": [
        {
          "title": "Format",
          "shortcuts": [
            {
              "title": "Format Document",
              "key": "shift+opt+f"
            }
          ]
        },
        {
          "title": "Editor",
          "shortcuts": [
            {
              "title": "Open Editor Tab",
              "key": "shift+cmd+e"
            },
            {
              "title": "Shrink Selection",
              "key": "ctrl+shift+left"
            },
            {
              "title": "Increase Selection",
              "key": "ctrl+shift+right"
            },
            {
              "title": "Cursor Selection PageUp",
              "key": "shift+pageup"
            },
            {
              "title": "Cursor Selection PageDown",
              "key": "shift+pagedown"
            }
          ]
        },
        {
          "title": "Refactor",
          "shortcuts": [
            {
              "title": "Rename",
              "key": "f2"
            }
          ]
        },
        {
          "title": "Navigation",
          "shortcuts": [
            {
              "title": "Open Global Keybindings",
              "key": "cmd+k cmd+s"
            }
          ]
        }
      ]
    },
    {
      "title": "Custom",
      "sections": [
        {
          "title": "Editor",
          "shortcuts": [
            {
              "title": "Open Editor Tab",
              "key": "shift+cmd+e"
            }
          ]
        }
      ]
    }
  ]
}

=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/1password.json
{
  "$schema": "schema/shortcut.schema.json",
  "name": "1Password",
  "slug": "1password",
  "bundleId": "com.1password.1password",
  "source": "https://support.1password.com/keyboard-shortcuts/",
  "keymaps": [
    {
      "title": "Default",
      "sections": [
        {
          "title": "1Password app",
          "shortcuts": [
            {
              "title": "View keyboard shortcuts",
              "key": "cmd+/"
            },
            {
              "title": "Open settings",
              "key": "cmd+,"
            },
            {
              "title": "Search for items",
              "key": "cmd+f"
            },
            {
              "title": "Find items in the current list",
              "key": "opt+cmd+f"
            },
            {
              "title": "Clear the search field",
              "key": "esc"
            },
            {
              "title": "Switch to All Accounts",
              "key": "cmd+1"
            },
            {
              "title": "Switch accounts and collections",
              "key": "cmd+2",
              "comment": "Accounts from 2 to 9"
            },
            {
              "title": "Go back",
              "key": "cmd+["
            },
            {
              "title": "Go forward",
              "key": "cmd+]"
            },
            {
              "title": "Focus next row",
              "key": "down"
            },
            {
              "title": "Focus previous row",
              "key": "up"
            },
            {
              "title": "Focus right section",
              "key": "right"
            },
            {
              "title": "Focus left section",
              "key": "left"
            },
            {
              "title": "Activate focused element",
              "key": "enter"
            },
            {
              "title": "Activate focused element",
              "key": "space"
            },
            {
              "title": "Copy the username or primary field of the item",
              "key": "cmd+c"
            },
            {
              "title": "Copy the password of the selected item",
              "key": "shift+cmd+c"
            },
            {
              "title": "Copy the one-time password of the selected item",
              "key": "opt+cmd+c"
            },
            {
              "title": "Open the website for the login in your browser",
              "key": "shift+cmd+f"
            },
            {
              "title": "Open the selected item in a new window",
              "key": "cmd+o"
            },
            {
              "title": "Create a new item",
              "key": "cmd+n"
            },
            {
              "title": "Edit the selected item",
              "key": "cmd+e"
            },
            {
              "title": "Save changes to an item",
              "key": "cmd+s"
            },
            {
              "title": "Cancel an edit",
              "key": "esc"
            },
            {
              "title": "Reveal or conceal secure fields in the item",
              "key": "cmd+r"
            },
            {
              "title": "Temporarily reveal all secure fields in the item",
              "comment": "Hold Option key"
            },
            {
              "title": "Move the selected item(s) to the Archive",
              "key": "backspace"
            },
            {
              "title": "Delete the selected item(s)",
              "key": "cmd+backspace"
            },
            {
              "title": "Collapse or expand the sidebar",
              "key": "shift+cmd+d"
            },
            {
              "title": "Zoom in",
              "key": "cmd+plus"
            },
            {
              "title": "Zoom out",
              "key": "cmd+-"
            },
            {
              "title": "Revert to actual size",
              "key": "cmd+0"
            },
            {
              "title": "Minimize the app to the Dock",
              "key": "cmd+m"
            },
            {
              "title": "Close the current window",
              "key": "cmd+w"
            }
          ]
        },
        {
          "title": "Quick Access",
          "shortcuts": [
            {
              "title": "Open or close Quick Access",
              "key": "shift+cmd+space"
            },
            {
              "title": "Clear the search field",
              "key": "esc"
            },
            {
              "title": "Switch accounts or collections",
              "key": "cmd+1 cmd+9"
            },
            {
              "title": "View all available actions",
              "key": "right"
            },
            {
              "title": "Copy username or primary field",
              "key": "cmd+c"
            },
            {
              "title": "Copy password",
              "key": "shift+cmd+c"
            },
            {
              "title": "Copy one-time password",
              "key": "opt+cmd+c"
            },
            {
              "title": "Open item details in new window",
              "key": "cmd+o"
            },
            {
              "title": "Open the website for the login in your browser",
              "key": "opt+enter"
            },
            {
              "title": "Fill the item in the currently focused app",
              "key": "shift+enter"
            },
            {
              "title": "Open the item in the app",
              "key": "shift+cmd+o"
            },
            {
              "title": "Lock 1Password",
              "key": "shift+cmd+l"
            },
            {
              "title": "Autofill",
              "key": "cmd+\\"
            }
          ]
        }
      ]
    }
  ]
}

=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/discord.json
{
  "$schema": "schema/shortcut.schema.json",
  "name": "Discord",
  "slug": "discord",
  "bundleId": "com.hnc.Discord",
  "keymaps": [
    {
      "title": "Default",
      "sections": [
        {
          "title": "Messages",
          "shortcuts": [
            {
              "title": "Edit message",
              "key": "e"
            },
            {
              "title": "Delete message",
              "key": "backspace"
            },
            {
              "title": "Pin message",
              "key": "p"
            },
            {
              "title": "Add reaction",
              "key": "plus"
            },
            {
              "title": "Reply",
              "key": "r"
            },
            {
              "title": "Mark unread",
              "key": "opt+enter"
            },
            {
              "title": "Copy text",
              "key": "cmd+c"
            },
            {
              "title": "Focus text area",
              "key": "esc"
            }
          ]
        },
        {
          "title": "Navigation",
          "shortcuts": [
            {
              "title": "Navigate between servers",
              "comment": "Use ⬆️ and ⬇️",
              "key": "opt+cmd+up"
            },
            {
              "title": "Navigate between channels",
              "comment": "Use ⬆️ and ⬇️",
              "key": "opt+up"
            },
            {
              "title": "Navigate between unread channels",
              "comment": "Use ⬆️ and ⬇️",
              "key": "shift+opt+up"
            },
            {
              "title": "Navigate between unread channels with mentions",
              "comment": "Use ⬆️ and ⬇️",
              "key": "shift+opt+cmd+up"
            },
            {
              "title": "Navigate forward and backward in page history",
              "comment": "Use [ and ]",
              "key": "shift+opt+["
            },
            {
              "title": "Navigate to current call",
              "key": "shift+opt+cmd+v"
            },
            {
              "title": "Toggle between last server and DMs",
              "key": "opt+cmd+right"
            },
            {
              "title": "Toggle QuickSwitcher",
              "key": "cmd+k"
            },
            {
              "title": "Create or join a server",
              "key": "shift+cmd+n"
            }
          ]
        },
        {
          "title": "Chat",
          "shortcuts": [
            {
              "title": "Mark server read",
              "key": "shift+esc"
            },
            {
              "title": "Mark channel read",
              "key": "esc"
            },
            {
              "title": "Create a private group",
              "key": "shift+cmd+t"
            },
            {
              "title": "Toggle pins popout",
              "key": "cmd+p"
            },
            {
              "title": "Toggle inbox popout",
              "key": "cmd+i"
            },
            {
              "title": "Mark top inbox channel read",
              "key": "shift+cmd+e"
            },
            {
              "title": "Toggle channel member list",
              "key": "cmd+u"
            },
            {
              "title": "Toggle emoji picker",
              "key": "cmd+e"
            },
            {
              "title": "Toggle GIF picker",
              "key": "cmd+g"
            },
            {
              "title": "Toggle sticker picker",
              "key": "cmd+s"
            },
            {
              "title": "Scroll chat up or down",
              "comment": "Use PgUp and PgDown",
              "key": "pageup"
            },
            {
              "title": "Upload a file",
              "key": "shift+cmd+u"
            },
            {
              "title": "Focus text area",
              "comment": "any key"
            },
            {
              "title": "Jump to oldest unread message",
              "key": "shift+pageup"
            }
          ]
        },
        {
          "title": "Voice and Video",
          "shortcuts": [
            {
              "title": "Toggle mute",
              "key": "shift+cmd+m"
            },
            {
              "title": "Toggle deafen",
              "key": "shift+cmd+d"
            },
            {
              "title": "Answer incoming call",
              "key": "cmd+enter"
            },
            {
              "title": "Decline incoming call",
              "key": "esc"
            },
            {
              "title": "Start call in private message or group",
              "key": "ctrl+'"
            },
            {
              "title": "Toggle soundboard",
              "key": "shift+cmd+b"
            }
          ]
        },
        {
          "title": "Miscellaneous",
          "shortcuts": [
            {
              "title": "Get help",
              "key": "shift+cmd+h"
            },
            {
              "title": "Search",
              "key": "cmd+f"
            },
            {
              "title": "Raging demon",
              "comment": "Only works from the hotkeys window",
              "key": "h h right n k"
            },
            {
              "title": "Listen to Lofi Beats with Wumpus",
              "key": "shift+opt+cmd+w"
            },
            {
              "title": "Toggle hotkeys window",
              "key": "cmd+/"
            }
          ]
        }
      ]
    }
  ]
}

=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/sqlpro-studio.json
{
  "$schema": "schema/shortcut.schema.json",
  "bundleId": "com.hankinsoft.sqlpro-studio-setapp",
  "name": "SQLPro Studio",
  "slug": "sqlpro-studio",
  "source": "https://github.com/hankinsoft/SQLPro/wiki/Keyboard-shortcuts",
  "keymaps": [
    {
      "title": "Default",
      "sections": [
        {
          "title": "General",
          "shortcuts": [
            {
              "title": "Opens the connection dialog",
              "key": "cmd+c"
            }
          ]
        },
        {
          "title": "Tab navigation",
          "shortcuts": [
            {
              "title": "Close the current tab.",
              "comment": "Closes the document if no tabs are open",
              "key": "cmd+w"
            },
            {
              "title": "Opens a new tab",
              "key": "cmd+t"
            },
            {
              "title": "Switches to the tab at that index",
              "comment": "Use 0-9",
              "key": "cmd+0"
            },
            {
              "title": "Switches to the next tab",
              "key": "shift+cmd+]"
            },
            {
              "title": "Switches to the previous tab",
              "key": "shift+cmd+["
            }
          ]
        },
        {
          "title": "Query Tab",
          "shortcuts": [
            {
              "title": "Run the current query",
              "key": "cmd+e"
            },
            {
              "title": "Display the history popup",
              "key": "shift+cmd+h"
            },
            {
              "title": "Display the database selector popup",
              "key": "shift+cmd+d"
            },
            {
              "title": "Hide/show the results grid",
              "key": "cmd+k"
            },
            {
              "title": "Comment/Uncomment query (Selection based)",
              "key": "cmd+-"
            },
            {
              "title": "Format query",
              "key": "shift+cmd+k"
            },
            {
              "title": "Goto line",
              "key": "shift+cmd+g"
            },
            {
              "title": "Move to matching bracket",
              "key": "ctrl+]"
            },
            {
              "title": "Show/hide autocomplete",
              "key": "esc"
            }
          ]
        },
        {
          "title": "Database Tree",
          "shortcuts": [
            {
              "title": "Default action for current item",
              "key": "cmd+down"
            },
            {
              "title": "Secondary action for current item",
              "key": "cmd+right"
            },
            {
              "title": "Hide/show database tree",
              "key": "cmd+l"
            }
          ]
        }
      ]
    }
  ]
}
