=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/schema/shortcut.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://hotkys.com/schema/shortcut.schema.json",
  "title": "Application shortcuts",
  "description": "A product in the catalog",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "Schema reference",
      "type": "string",
      "const": "schema/shortcut.schema.json"
    },
    "bundleId": {
      "description": "Bundle id is a unique identifier for the macOS application. Example: 'com.microsoft.VSCode'",
      "type": "string",
      "minLength": 1
    },
    "hostname": {
      "description": "Hostname of the web application. Example: 'code.visualstudio.com'",
      "type": "string",
      "minLength": 1
    },
    "slug": {
      "description": "Unique readable identifier",
      "type": "string",
      "minLength": 1,
      "pattern": "^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$"
    },
    "name": {
      "description": "Name of the application",
      "type": "string",
      "minLength": 1
    },
    "source": {
      "description": "Link to the source of the shortcuts",
      "type": "string",
      "format": "uri"
    },
    "keymaps": {
      "description": "List of the application keymaps. Most of the applications have single keymap that should be named 'Default'.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/keymap"
      },
      "minItems": 1
    }
  },
  "required": ["$schema", "name", "slug", "keymaps"],
  "additionalProperties": false,
  "$defs": {
    "keymap": {
      "description": "Application keymap. Keymap is a shortcut configuration.",
      "type": "object",
      "properties": {
        "title": {
          "description": "Keymap title",
          "type": "string",
          "minLength": 1
        },
        "sections": {
          "description": "List of sections",
          "type": "array",
          "items": {
            "$ref": "#/$defs/section"
          },
          "minItems": 1
        }
      },
      "required": ["title", "sections"],
      "additionalProperties": false
    },
    "section": {
      "description": "Section with shortcuts or category. Examples: Edit, Navigate, Format.",
      "type": "object",
      "properties": {
        "title": {
          "description": "Section title",
          "type": "string",
          "minLength": 1
        },
        "shortcuts": {
          "description": "List of shortcuts",
          "type": "array",
          "items": {
            "$ref": "#/$defs/section-shortcut"
          },
          "minItems": 1
        }
      },
      "required": ["title", "shortcuts"],
      "additionalProperties": false
    },
    "section-shortcut": {
      "description": "Shortcut with title and key",
      "type": "object",
      "properties": {
        "title": {
          "description": "Shortcut title",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "key": {
          "description": "Shortcut key definition. Key consist of modifiers plus base key separated by '+' sign. Supported modifiers: 'ctrl', 'shift', 'opt', 'cmd'. Modifiers should be specified in that exact order, lowercase. Final shortcut token should always be a base key. Examples: 'ctrl+s', 'shift+cmd+e'. Shortcut macro or sequences of shortcuts are also supported and should be separated by whitespace (' '). Example: 'cmd+k cmd+s'",
          "type": "string",
          "minLength": 1
        },
        "comment": {
          "description": "Text comment for the shortcut. Can be used as a substitute or addition to the declared key",
          "type": "string",
          "maxLength": 50
        }
      },
      "required": ["title"],
      "anyOf": [
        {
          "required": [
            "key"
          ]
        },
        {
          "required": [
            "comment"
          ]
        }
      ],
      "additionalProperties": false
    }
  }
}

=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/intellij-idea.json
{
  "$schema": "schema/shortcut.schema.json",
  "bundleId": "com.jetbrains.intellij",
  "name": "IntelliJ IDEA",
  "slug": "intellij-idea",
  "keymaps": [
    {
      "title": "Default",
      "sections": [
        {
          "title": "Popular",
          "shortcuts": [
            {
              "title": "Search everywhere",
              "key": "shift shift"
            },
            {
              "title": "Find action...",
              "key": "shift+cmd+a"
            },
            {
              "title": "Show Project window",
              "key": "cmd+1"
            },
            {
              "title": "Rebuild",
              "key": "shift+cmd+f9"
            },
            {
              "title": "Show Intention Actions",
              "key": "opt+enter"
            },
            {
              "title": "Recent files",
              "key": "cmd+e"
            },
            {
              "title": "Find usages",
              "key": "opt+f7"
            },
            {
              "title": "Select in...",
              "key": "opt+f1"
            },
            {
              "title": "Settings",
              "key": "cmd+,"
            },
            {
              "title": "Generate",
              "key": "cmd+n"
            },
            {
              "title": "Run anything",
              "key": "ctrl ctrl"
            },
            {
              "title": "Debug",
              "key": "ctrl+opt+d"
            },
            {
              "title": "View breakpoints",
              "key": "shift+cmd+f8"
            },
            {
              "title": "Attach to process",
              "key": "shift+opt+f5"
            },
            {
              "title": "VCS operations popup",
              "key": "ctrl+v"
            },
            {
              "title": "Refactor this",
              "key": "ctrl+t"
            },
            {
              "title": "Reformat code",
              "key": "opt+cmd+l"
            }
          ]
        },
        {
          "title": "Navigation",
          "shortcuts": [
            {
              "title": "Recent files",
              "key": "cmd+e"
            },
            {
              "title": "Open window in floating mode",
              "key": "shift+f4"
            }
          ]
        },
        {
          "title": "Version Control System",
          "shortcuts": [
            {
              "title": "Update project",
              "key": "cmd+t"
            },
            {
              "title": "Commit project",
              "key": "cmd+k"
            },
            {
              "title": "Push commits",
              "key": "shift+cmd+k"
            },
            {
              "title": "Push commits with force push",
              "key": "shift+cmd+k shift+opt+enter enter"
            },
            {
              "title": "Pull changes",
              "key": "shift+cmd+k"
            }
          ]
        }
      ]
    }
  ]
}

=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/safari.json
{
  "$schema": "schema/shortcut.schema.json",
  "bundleId": "com.apple.Safari",
  "name": "Safari",
  "slug": "safari",
  "keymaps": [
    {
      "title": "Default",
      "sections": [
        {
          "title": "Bookmarks",
          "shortcuts": [
            {
              "title": "Open Bookmarks Manager",
              "key": "opt+cmd+b"
            }
          ]
        },
        {
          "title": "Current Webpage",
          "shortcuts": [
            {
              "title": "Search the current webpage",
              "key": "cmd+f"
            },
            {
              "title": "Select the Smart Search field",
              "key": "cmd+l"
            },
            {
              "title": "Print the current webpage",
              "key": "cmd+p"
            }
          ]
        },
        {
          "title": "Tabs",
          "shortcuts": [
            {
              "title": "Show tab overview",
              "key": "shift+cmd+\\"
            },
            {
              "title": "Go to the next tab",
              "key": "ctrl+tab"
            },
            {
              "title": "Go to the previous tab",
              "key": "ctrl+shift+tab"
            }
          ]
        },
        {
          "title": "Develop",
          "shortcuts": [
            {
              "title": "Toggle Responsive Design Mode",
              "key": "ctrl+cmd+r"
            },
            {
              "title": "Empty Caches",
              "key": "opt+cmd+e"
            },
            {
              "title": "Show Web Inspector",
              "key": "opt+cmd+i"
            },
            {
              "title": "Show JavaScript Console",
              "key": "opt+cmd+c"
            },
            {
              "title": "Show Page Source",
              "key": "opt+cmd+u"
            },
            {
              "title": "Show Page Resources",
              "key": "opt+cmd+a"
            }
          ]
        }
      ]
    }
  ]
}

=== solomkinmv/hotkys/shortcuts-site/shortcuts-data/obsidian.json
{
  "$schema": "schema/shortcut.schema.json",
  "name": "Obsidian",
  "bundleId": "md.obsidian",
  "slug": "obsidian",
  "keymaps": [
    {
      "title": "Default",
      "sections": [
        {
          "title": "Note",
          "shortcuts": [
            {
              "title": "Create new note",
              "key": "cmd+n"
            },
            {
              "title": "Create note to the right",
              "key": "shift+cmd+n"
            },
            {
              "title": "Add file property",
              "key": "cmd+;"
            },
            {
              "title": "Delete paragraph",
              "key": "cmd+d"
            },
            {
              "title": "Insert Markdown link",
              "key": "cmd+k"
            },
            {
              "title": "Toggle bold",
              "key": "cmd+b"
            },
            {
              "title": "Toggle checkbox status",
              "key": "cmd+l"
            },
            {
              "title": "Toggle comment",
              "key": "cmd+/"
            },
            {
              "title": "Toggle italics",
              "key": "cmd+i"
            },
            {
              "title": "Toggle reading view",
              "key": "cmd+e"
            }
          ]
        },
        {
          "title": "Navigation",
          "shortcuts": [
            {
              "title": "Open quickly",
              "key": "cmd+o"
            },
            {
              "title": "Go to next tab",
              "key": "shift+cmd+]"
            },
            {
              "title": "Go to previous tab",
              "key": "shift+cmd+["
            },
            {
              "title": "Follow link under cursor",
              "key": "opt+enter"
            },
            {
              "title": "Navigate back",
              "key": "opt+cmd+left"
            },
            {
              "title": "Navigate forward",
              "key": "opt+cmd+right"
            },
            {
              "title": "Close current tab",
              "key": "cmd+w"
            },
            {
              "title": "Undo close tab",
              "key": "shift+cmd+t"
            },
            {
              "title": "New tab",
              "key": "cmd+t"
            },
            {
              "title": "Rename file",
              "key": "f2"
            },
            {
              "title": "Search current file",
              "key": "cmd+f"
            },
            {
              "title": "Search in all files",
              "key": "shift+cmd+f"
            }
          ]
        },
        {
          "title": "Windows",
          "shortcuts": [
            {
              "title": "Close window",
              "key": "shift+cmd+w"
            },
            {
              "title": "Open help",
              "key": "f1"
            },
            {
              "title": "Open settings",
              "key": "cmd+,"
            }
          ]
        }
      ]
    }
  ]
}

=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/microsoft-outlook.json
{
  "$schema": "schema/shortcut.schema.json",
  "bundleId": "com.microsoft.Outlook",
  "name": "Microsoft Outlook",
  "slug": "microsoft-outlook",
  "keymaps": [
    {
      "title": "Default",
      "sections": [
        {
          "title": "General Shortcuts",
          "shortcuts": [
            {
              "title": "General Shortcuts",
              "key": "cmd+o"
            },
            {
              "title": "Close an open item",
              "key": "cmd+w"
            },
            {
              "title": "Flag an item for follow-up",
              "key": "ctrl+5"
            },
            {
              "title": "Go to the search box",
              "key": "opt+cmd+f"
            },
            {
              "title": "Use advanced find",
              "key": "shift+cmd+f"
            },
            {
              "title": "Check spelling and grammar",
              "key": "cmd+;"
            },
            {
              "title": "Make text bold",
              "key": "cmd+b"
            },
            {
              "title": "Make text italic",
              "key": "cmd+i"
            },
            {
              "title": "Add bullets",
              "key": "shift+cmd+l"
            },
            {
              "title": "Switch to mail",
              "key": "cmd+1"
            },
            {
              "title": "Switch to calendar",
              "key": "cmd+2"
            },
            {
              "title": "Switch to contacts",
              "key": "cmd+3"
            },
            {
              "title": "Switch to tasks",
              "key": "cmd+4"
            },
            {
              "title": "Switch to notes",
              "key": "cmd+5"
            }
          ]
        },
        {
          "title": "Email",
          "shortcuts": [
            {
              "title": "Create a new message",
            "key": "cmd+n"
            },
            {
              "title": "Mark message as read",
              "key": "cmd+t"
            },
            {
              "title": "Mark message as unread",
              "key": "shift+cmd+t"
            },
            {
              "title": "Move message to a folder",
              "key": "shift+cmd+m"
            },
            {
              "title": "Send a message",
              "key": "cmd+enter"
            },
            {
              "title": "Reply",
              "key": "cmd+r"
            },
            {
              "title": "Reply all",
              "key": "shift+cmd+r"
            },
            {
              "title": "Forward",
              "key": "cmd+j"
            },
            {
              "title": "Attach a file to a message",
              "key": "cmd+e"
            },
            {
              "title": "Create a folder",
              "key": "shift+cmd+n"
            }
          ]
        }
      ]
    }
  ]
}

=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/omnifocus3.json
{
  "$schema": "schema/shortcut.schema.json",
  "bundleId": "com.omnigroup.OmniFocus3",
  "name": "OmniFocus 3",
  "slug": "omnifocus3",
  "keymaps": [
    {
      "title": "Default",
      "sections": [
        {
          "title": "File",
          "shortcuts": [
            {
              "title": "New Action",
              "key": "cmd+n"
            },
            {
              "title": "New Project",
              "key": "shift+cmd+n"
            },
            {
              "title": "New Tag",
              "key": "ctrl+cmd+n"
            },
            {
              "title": "New Window",
              "key": "opt+cmd+n"
            },
            {
              "title": "New Tab",
              "key": "opt+cmd+t"
            },
            {
              "title": "Quick Openâ€¦",
              "key": "cmd+o"
            },
            {
              "title": "Close Window",
              "key": "cmd+w"
            },
            {
              "title": "Close All",
              "key": "opt+cmd+w"
            },
            {
              "title": "Sync Now",
              "key": "cmd+s"
            },
            {
              "title": "Page Setupâ€¦",
              "key": "shift+cmd+p"
            },
            {
              "title": "Printâ€¦",
              "key": "cmd+p"
            }
          ]
        },
        {
          "title": "Edit",
          "shortcuts": [
            {
              "title": "Undo",
              "key": "cmd+z"
            },
            {
              "title": "Redo",
              "key": "shift+cmd+z"
            },
            {
              "title": "Cut",
              "key": "cmd+x"
            },
            {
              "title": "Copy",
              "key": "cmd+c"
            },
            {
              "title": "Paste",
              "key": "cmd+v"
            },
            {
              "title": "Paste and Match Style",
              "key": "shift+opt+cmd+v"
            },
            {
              "title": "Paste and Simplify Style",
              "key": "ctrl+shift+opt+cmd+v"
            },
            {
              "title": "Select All",
              "key": "cmd+a"
            },
            {
              "title": "Deselect All",
              "key": "shift+cmd+a"
            },
            {
              "title": "Duplicate",
              "key": "cmd+d"
            },
            {
              "title": "Edit Note",
              "key": "cmd+'"
            },
            {
              "title": "Convert to Project",
              "key": "shift+cmd+1"
            },
            {
              "title": "Mark Reviewed",
              "key": "shift+cmd+r"
            },
            {
              "title": "Add Forecast Tag",
              "key": "ctrl+cmd+l"
            },
            {
              "title": "Set Flag",
              "key": "shift+cmd+l"
            },
            {
              "title": "Go to Search Field",
              "key": "opt+cmd+f"
            },
            {
              "title": "Findâ€¦",
              "key": "cmd+f"
            },
            {
              "title": "Find Next",
              "key": "cmd+g"
            },
            {
              "title": "Find Previous",
              "key": "shift+cmd+g"
            },
            {
              "title": "Use Selection for Find",
              "key": "cmd+e"
            },
            {
              "title": "Jump to Selection",
              "key": "cmd+j"
            },
            {
              "title": "Show Spelling and Grammar",
              "key": "shift+cmd+;"
            },
            {
              "title": "Check Document Now",
              "key": "cmd+;"
            },
            {
              "title": "Start Dictationâ€¦",
              "comment": "ðŸŽ¤"
            },
            {
              "title": "Emoji & Symbols",
              "comment": "fn+e"
            }
          ]
        },
        {
          "title": "Organize",
          "shortcuts": [
            {
              "title": "Clean Up",
              "key": "cmd+k"
            },
            {
              "title": "Add Inside",
              "key": "shift+cmd+]"
            },
            {
              "title": "Add Outside",
              "key": "shift+cmd+["
            },
            {
              "title": "Move Down",
              "key": "ctrl+cmd+down"
            },
            {
              "title": "Move Right",
              "key": "ctrl+cmd+right"
            },
            {
              "title": "Move Up",
              "key": "ctrl+cmd+up"
            },
            {
              "title": "Move Left",
              "key": "ctrl+cmd+left"
            },
            {
              "title": "Indent",
              "key": "cmd+]"
            },
            {
              "title": "Outdent",
              "key": "cmd+["
            },
            {
              "title": "Group",
              "key": "opt+cmd+g"
            },
            {
              "title": "Ungroup",
              "key": "opt+cmd+u"
            }
          ]
        },
        {
          "title": "View",
          "shortcuts": [
            {
              "title": "Expand All",
              "key": "ctrl+cmd+9"
            },
            {
              "title": "Collapse All",
              "key": "ctrl+cmd+0"
            },
            {
              "title": "Expand Item",
              "key": "cmd+9"
            },
            {
              "title": "Expand Item Completely",
              "key": "opt+cmd+9"
            },
            {
              "title": "Collapse Item",
              "key": "cmd+0"
            },
            {
              "title": "Collapse Item Completely",
              "key": "opt+cmd+0"
            },
            {
              "title": "Show All Notes",
              "key": "ctrl+cmd+'"
            },
            {
              "title": "Show Note",
              "key": "opt+cmd+'"
            },
            {
              "title": "Focus on Selected Projects",
              "key": "shift+cmd+f"
            },
            {
              "title": "Show in Projects",
              "key": "opt+cmd+r"
            },
            {
              "title": "Show Sidebar",
              "key": "opt+cmd+s"
            },
            {
              "title": "Show Inspector",
              "key": "opt+cmd+i"
            },
            {
              "title": "Go to Sidebar",
              "key": "opt+cmd+1"
            },
            {
              "title": "Go to Outline",
              "key": "opt+cmd+2"
            },
            {
              "title": "Go to Inspector",
              "key": "opt+cmd+3"
            },
            {
              "title": "Show View Options",
              "key": "shift+cmd+v"
            },
            {
              "title": "Show All Tabs",
              "key": "shift+cmd+\\"
            },
            {
              "title": "Enter Full Screen",
              "comment": "fn+f"
            }
          ]
        },
        {
          "title": "Perspectives",
          "shortcuts": [
            {
              "title": "Show Perspectives",
              "key": "ctrl+cmd+p"
            },
            {
              "title": "Inbox",
              "key": "cmd+1"
            },
            {
              "title": "Projects",
              "key": "cmd+2"
            },
            {
              "title": "Tags",
              "key": "cmd+3"
            },
            {
              "title": "Forecast",
              "key": "cmd+4"
            },
            {
              "title": "Flagged",
              "key": "cmd+5"
            },
            {
              "title": "Review",
              "key": "cmd+6"
            }
          ]
        },
        {
          "title": "Format",
          "shortcuts": [
            {
              "title": "Copy Style",
              "key": "opt+cmd+c"
            },
            {
              "title": "Paste Style",
              "key": "opt+cmd+v"
            },
            {
              "title": "Clear Style",
              "key": "ctrl+cmd+backspace"
            },
            {
              "title": "Show Fonts",
              "key": "cmd+t"
            },
            {
              "title": "Show Colors",
              "key": "shift+cmd+c"
            },
            {
              "title": "Bold",
              "key": "cmd+b"
            },
            {
              "title": "Italic",
              "key": "cmd+i"
            },
            {
              "title": "Underline",
              "key": "cmd+u"
            },
            {
              "title": "Bigger",
              "key": "shift+cmd+="
            },
            {
              "title": "Smaller",
              "key": "cmd+-"
            }
          ]
        },
        {
          "title": "Window",
          "shortcuts": [
            {
              "title": "Minimize Window",
              "key": "cmd+m"
            },
            {
              "title": "Minimize All Windows",
              "key": "opt+cmd+m"
            },
            {
              "title": "Show Quick Entry",
              "key": "ctrl+shift+opt+space"
            }
          ]
        }
      ]
    }
  ]
}
