=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/schema/shortcut.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://hotkys.com/schema/shortcut.schema.json",
  "title": "Application shortcuts",
  "description": "A product in the catalog",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "Schema reference",
      "type": "string",
      "const": "schema/shortcut.schema.json"
    },
    "bundleId": {
      "description": "Bundle id is a unique identifier for the macOS application. Example: 'com.microsoft.VSCode'",
      "type": "string",
      "minLength": 1
    },
    "hostname": {
      "description": "Hostname of the web application. Example: 'code.visualstudio.com'",
      "type": "string",
      "minLength": 1
    },
    "slug": {
      "description": "Unique readable identifier",
      "type": "string",
      "minLength": 1,
      "pattern": "^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$"
    },
    "name": {
      "description": "Name of the application",
      "type": "string",
      "minLength": 1
    },
    "source": {
      "description": "Link to the source of the shortcuts",
      "type": "string",
      "format": "uri"
    },
    "keymaps": {
      "description": "List of the application keymaps. Most of the applications have single keymap that should be named 'Default'.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/keymap"
      },
      "minItems": 1
    }
  },
  "required": ["$schema", "name", "slug", "keymaps"],
  "additionalProperties": false,
  "$defs": {
    "keymap": {
      "description": "Application keymap. Keymap is a shortcut configuration.",
      "type": "object",
      "properties": {
        "title": {
          "description": "Keymap title",
          "type": "string",
          "minLength": 1
        },
        "sections": {
          "description": "List of sections",
          "type": "array",
          "items": {
            "$ref": "#/$defs/section"
          },
          "minItems": 1
        }
      },
      "required": ["title", "sections"],
      "additionalProperties": false
    },
    "section": {
      "description": "Section with shortcuts or category. Examples: Edit, Navigate, Format.",
      "type": "object",
      "properties": {
        "title": {
          "description": "Section title",
          "type": "string",
          "minLength": 1
        },
        "shortcuts": {
          "description": "List of shortcuts",
          "type": "array",
          "items": {
            "$ref": "#/$defs/section-shortcut"
          },
          "minItems": 1
        }
      },
      "required": ["title", "shortcuts"],
      "additionalProperties": false
    },
    "section-shortcut": {
      "description": "Shortcut with title and key",
      "type": "object",
      "properties": {
        "title": {
          "description": "Shortcut title",
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "key": {
          "description": "Shortcut key definition. Key consist of modifiers plus base key separated by '+' sign. Supported modifiers: 'ctrl', 'shift', 'opt', 'cmd'. Modifiers should be specified in that exact order, lowercase. Final shortcut token should always be a base key. Examples: 'ctrl+s', 'shift+cmd+e'. Shortcut macro or sequences of shortcuts are also supported and should be separated by whitespace (' '). Example: 'cmd+k cmd+s'",
          "type": "string",
          "minLength": 1
        },
        "comment": {
          "description": "Text comment for the shortcut. Can be used as a substitute or addition to the declared key",
          "type": "string",
          "maxLength": 50
        }
      },
      "required": ["title"],
      "anyOf": [
        {
          "required": [
            "key"
          ]
        },
        {
          "required": [
            "comment"
          ]
        }
      ],
      "additionalProperties": false
    }
  }
}

=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/google-chrome.json
{
  "$schema": "schema/shortcut.schema.json",
  "bundleId": "com.google.Chrome",
  "name": "Google Chrome",
  "slug": "google-chrome",
  "keymaps": [
    {
      "title": "Default",
      "sections": [
        {
          "title": "Chrome Window and Tabs",
          "shortcuts": [
            {
              "title": "Open a New Window",
              "key": "cmd+n"
            },
            {
              "title": "Open a New Incognito Window",
              "key": "shift+cmd+n"
            },
            {
              "title": "Enter/Exit Full Screen Mode",
              "key": "ctrl+cmd+f"
            },
            {
              "title": "Minimize the Window",
              "key": "cmd+m"
            },
            {
              "title": "Hide the Window",
              "key": "cmd+h"
            },
            {
              "title": "Close a Window",
              "key": "shift+cmd+w"
            },
            {
              "title": "Quit Chrome",
              "key": "cmd+q"
            },
            {
              "title": "Open a New Tab",
              "key": "cmd+t"
            },
            {
              "title": "Close Current Tab",
              "key": "cmd+w"
            },
            {
              "title": "Reopen Closed Tab",
              "key": "shift+cmd+t"
            },
            {
              "title": "Jump to Address Bar",
              "key": "cmd+l"
            },
            {
              "title": "Select Tab 1",
              "key": "cmd+1",
              "comment": "Can be used with digits 1 to 8"
            },
            {
              "title": "Select the Last Tab",
              "key": "cmd+9"
            },
            {
              "title": "Move to Next Tab",
              "key": "opt+cmd+right"
            },
            {
              "title": "Move to Previous Tab",
              "key": "opt+cmd+left"
            }
          ]
        },
        {
          "title": "Webpage Navigation",
          "shortcuts": [
            {
              "title": "Reload Page",
              "key": "cmd+r"
            },
            {
              "title": "Reload and Ignore Cache",
              "key": "shift+cmd+r"
            },
            {
              "title": "Zoom In",
              "key": "cmd+plus"
            },
            {
              "title": "Zoom Out",
              "key": "cmd+hyphen"
            },
            {
              "title": "Reset Zoom",
              "key": "cmd+0"
            },
            {
              "title": "Move Down a Screen",
              "key": "space"
            },
            {
              "title": "Move Up a Screen",
              "key": "shift+space"
            },
            {
              "title": "Save the Page",
              "key": "cmd+s"
            },
            {
              "title": "Save the Page as a Bookmark",
              "key": "cmd+d"
            },
            {
              "title": "Save Open Tabs in a New Bookmarks Folder",
              "key": "shift+cmd+d"
            },
            {
              "title": "Print the Page",
              "key": "cmd+p"
            },
            {
              "title": "Go to the Address Bar",
              "key": "cmd+l"
            },
            {
              "title": "Move Cursor to the Address Bar",
              "key": "ctrl+f5"
            },
            {
              "title": "Search with Default Search Engine",
              "comment": "type term then return"
            },
            {
              "title": "Search with a Different Search Engine",
              "comment": "type search engine then tab"
            },
            {
              "title": "Open a Website in a Background Tab",
              "comment": "type web address then return"
            },
            {
              "title": "Complete 'www.' and '.com' for Current Tab",
              "key": "ctrl+enter"
            },
            {
              "title": "Complete 'www.' and '.com' for New Tab",
              "key": "ctrl+shift+enter"
            }
          ]
        },
        {
          "title": "Chrome Features",
          "shortcuts": [
            {
              "title": "Toggle the Bookmarks Bar",
              "key": "shift+cmd+b"
            },
            {
              "title": "Open the Bookmarks Manager",
              "key": "opt+cmd+b"
            },
            {
              "title": "Open the History Page",
              "key": "cmd+y"
            },
            {
              "title": "Open the Downloads Page",
              "key": "shift+cmd+j"
            },
            {
              "title": "Chrome Task Manager",
              "key": "shift+esc"
            },
            {
              "title": "Open the Find Bar to Search the Page",
              "key": "cmd+f"
            },
            {
              "title": "Log in as a Different User",
              "key": "shift+cmd+m"
            },
            {
              "title": "Open Developer Tools",
              "key": "opt+cmd+j"
            },
            {
              "title": "Open Clear Data Options",
              "key": "shift+cmd+backspace"
            },
            {
              "title": "Open the Settings Page",
              "key": "cmd+,"
            }
          ]
        },
        {
          "title": "Development",
          "shortcuts": [
            {
              "title": "Open Developer Tools",
              "key": "opt+cmd+j"
            },
            {
              "title": "Open the JavaScript Console",
              "key": "opt+cmd+j"
            },
            {
              "title": "Inspect Elements",
              "key": "shift+cmd+c"
            },
            {
              "title": "View Page Source",
              "key": "opt+cmd+u"
            },
            {
              "title": "Open the Task Manager",
              "key": "shift+esc"
            },
            {
              "title": "Reload the Page, Ignoring Cached Content",
              "key": "shift+cmd+r"
            },
            {
              "title": "Show or Hide the Bookmarks Bar",
              "key": "shift+cmd+b"
            },
            {
              "title": "Open the History Page",
              "key": "cmd+y"
            },
            {
              "title": "Open the Downloads Page",
              "key": "shift+cmd+j"
            },
            {
              "title": "Open Chrome Settings",
              "key": "cmd+,"
            },
            {
              "title": "Navigate to the Next Match Within the Inspector",
              "key": "cmd+g"
            },
            {
              "title": "Navigate to Previous Match Within the Inspector",
              "key": "shift+cmd+g"
            },
            {
              "title": "Take a Screenshot of the Visible Area",
              "key": "shift+cmd+p",
              "comment": "then type 'Screenshot'"
            }
          ]
        }
      ]
    }
  ]
}

=== solomkinmv/hotkys/shortcuts-site/shortcuts-data/xcode.json
{
  "$schema": "schema/shortcut.schema.json",
  "bundleId": "com.apple.dt.Xcode",
  "name": "Xcode",
  "slug": "xcode",
  "keymaps": [
    {
      "title": "Default",
      "sections": [
        {
          "title": "Build",
          "shortcuts": [
            {
              "title": "Run",
              "key": "cmd+r"
            },
            {
              "title": "Build",
              "key": "cmd+b"
            }
          ]
        },
        {
          "title": "Format",
          "shortcuts": [
            {
              "title": "Re-Indent",
              "key": "ctrl+i"
            }
          ]
        },
        {
          "title": "Editor",
          "shortcuts": [
            {
              "title": "Show library pop-up",
              "key": "shift+cmd+l"
            },
            {
              "title": "Show library window",
              "key": "shift+opt+cmd+l"
            }
          ]
        }
      ]
    }
  ]
}

=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/firefox.json
{
  "$schema": "schema/shortcut.schema.json",
  "bundleId": "org.mozilla.firefox",
  "name": "Firefox",
  "slug": "firefox",
  "keymaps": [
    {
      "title": "Default",
      "sections": [
        {
          "title": "Windows & Tabs",
          "shortcuts": [
            {
              "title": "Close Tab",
              "key": "cmd+w"
            },
            {
              "title": "Close Window",
              "key": "shift+cmd+w"
            },
            {
              "title": "New Tab",
              "key": "cmd+t"
            },
            {
              "title": "New Window",
              "key": "cmd+n"
            },
            {
              "title": "New Private Window",
              "key": "shift+cmd+p"
            },
            {
              "title": "Undo Close Tab",
              "key": "shift+cmd+t"
            },
            {
              "title": "Undo Close Window",
              "key": "shift+cmd+n"
            },
            {
              "title": "Move Tab Left",
              "key": "ctrl+shift+pageup"
            },
            {
              "title": "Move Tab Right",
              "key": "ctrl+shift+pagedown"
            }
          ]
        },
        {
          "title": "History",
          "shortcuts": [
            {
              "title": "History Sidebar",
              "key": "shift+cmd+h"
            },
            {
              "title": "Clear Recent History",
              "key": "shift+cmd+backspace"
            }
          ]
        },
        {
          "title": "Bookmarks",
          "shortcuts": [
            {
              "title": "Bookmark This Page",
              "key": "cmd+d"
            },
            {
              "title": "Bookmark All Tabs",
              "key": "shift+cmd+d"
            },
            {
              "title": "Bookmarks Sidebar",
              "key": "cmd+b"
            },
            {
              "title": "Show All Bookmarks",
              "key": "shift+cmd+b"
            }
          ]
        },
        {
          "title": "Page Navigation",
          "shortcuts": [
            {
              "title": "Back",
              "key": "cmd+left"
            },
            {
              "title": "Forward",
              "key": "cmd+right"
            },
            {
              "title": "Reload",
              "key": "cmd+r"
            },
            {
              "title": "Reload and Override Cache",
              "key": "shift+cmd+r"
            },
            {
              "title": "Save Page",
              "key": "cmd+s"
            },
            {
              "title": "Print Page",
              "key": "cmd+p"
            },
            {
              "title": "Zoom In",
              "key": "cmd++"
            },
            {
              "title": "Zoom Out",
              "key": "cmd+-"
            },
            {
              "title": "Reset Zoom",
              "key": "cmd+0"
            }
          ]
        },
        {
          "title": "Searching in Firefox",
          "shortcuts": [
            {
              "title": "Find",
              "key": "cmd+f"
            },
            {
              "title": "Find Again",
              "key": "cmd+g"
            },
            {
              "title": "Find Previous",
              "key": "shift+cmd+g"
            },
            {
              "title": "Quick Find",
              "key": "/"
            },
            {
              "title": "Close Find or Quick Find bar",
              "key": "esc"
            },
            {
              "title": "Focus Search Bar",
              "key": "cmd+k"
            }
          ]
        },
        {
          "title": "Miscellaneous",
          "shortcuts": [
            {
              "title": "Complete .com Address",
              "key": "ctrl+enter"
            },
            {
              "title": "Delete Selected Autocomplete Entry",
              "key": "shift+backspace"
            },
            {
              "title": "Toggle Full Screen",
              "key": "shift+cmd+f"
            },
            {
              "title": "Toggle Reader Mode",
              "key": "opt+cmd+r"
            },
            {
              "title": "Caret Browsing",
              "key": "f7"
            },
            {
              "title": "Focus Address Bar",
              "key": "f6"
            },
            {
              "title": "Focus Address Bar",
              "key": "f6"
            },
            {
              "title": "Focus Address Bar",
              "key": "cmd+l"
            },
            {
              "title": "Focus Search Field in Library",
              "key": "f6"
            },
            {
              "title": "Focus Search Field in Library",
              "key": "cmd+f"
            }
          ]
        },
        {
          "title": "Media Controls",
          "shortcuts": [
            {
              "title": "Toggle Play/Pause",
              "key": "space"
            },
            {
              "title": "Decrease Volume",
              "key": "down"
            },
            {
              "title": "Increase Volume",
              "key": "up"
            },
            {
              "title": "Mute Audio",
              "key": "ctrl+m"
            }
          ]
        },
        {
          "title": "Developer Tools",
          "shortcuts": [
            {
              "title": "Toggle Developer Tools",
              "key": "f12"
            },
            {
              "title": "Toggle Developer Tools",
              "key": "opt+cmd+i"
            },
            {
              "title": "Web Console",
              "key": "opt+cmd+k"
            },
            {
              "title": "Inspector",
              "key": "opt+cmd+c"
            },
            {
              "title": "Take a Screenshot",
              "key": "shift+cmd+s"
            },
            {
              "title": "Style Editor",
              "key": "shift+f7"
            }
          ]
        }
      ]
    }
  ]
}

=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/freeform.json
{
  "$schema": "schema/shortcut.schema.json",
  "bundleId": "com.apple.freeform",
  "name": "Freeform",
  "slug": "freeform",
  "keymaps": [
    {
      "title": "Default",
      "sections": [
        {
          "title": "File",
          "shortcuts": [
            {
              "title": "New board",
              "key": "cmd+n"
            },
            {
              "title": "New tab",
              "key": "cmd+t"
            },
            {
              "title": "New window",
              "key": "shift+cmd+n"
            },
            {
              "title": "Close",
              "key": "cmd+w"
            }
          ]
        },
        {
          "title": "View",
          "shortcuts": [
            {
              "title": "Toggle sidebar",
              "key": "ctrl+cmd+s"
            },
            {
              "title": "Zoom in",
              "key": "cmd++"
            },
            {
              "title": "Zoom out",
              "key": "cmd+-"
            },
            {
              "title": "Actual size",
              "key": "cmd+0"
            },
            {
              "title": "Zoom to selection",
              "key": "shift+cmd+0"
            },
            {
              "title": "Zoom to fit content",
              "key": "shift+opt+cmd+o"
            }
          ]
        }
      ]
    }
  ]
}

=== solomkinmv/hotkys/shortcuts-disco-site/shortcuts-data/spotify.json
{
  "$schema": "schema/shortcut.schema.json",
  "name": "Spotify",
  "slug": "spotify",
  "bundleId": "com.spotify.client",
  "source": "https://support.spotify.com/is-en/using_spotify/system_settings/keyboard-shortcuts/",
  "keymaps": [
    {
      "title": "Default",
      "sections": [
        {
          "title": "Basic",
          "shortcuts": [
            {
              "title": "Create new playlist",
              "key": "cmd+n"
            },
            {
              "title": "Create new folder",
              "key": "shift+cmd+n"
            },
            {
              "title": "Open context menu",
              "key": "opt+j"
            },
            {
              "title": "Open Quick Search",
              "key": "opt+k"
            },
            {
              "title": "Select all",
              "key": "cmd+a"
            },
            {
              "title": "Filter (in Songs and Playlists)",
              "key": "cmd+f"
            },
            {
              "title": "Search in Your Library",
              "key": "opt+cmd+f"
            },
            {
              "title": "Log out",
              "key": "shift+cmd+f6"
            }
          ]
        },
        {
          "title": "Playback",
          "shortcuts": [
            {
              "title": "Play / Pause",
              "key": "space"
            },
            {
              "title": "Like",
              "key": "shift+opt+b"
            },
            {
              "title": "Shuffle",
              "key": "cmd+s"
            },
            {
              "title": "Repeat",
              "key": "cmd+r"
            },
            {
              "title": "Skip to previous",
              "key": "cmd+left"
            },
            {
              "title": "Skip to next",
              "key": "cmd+right"
            },
            {
              "title": "Seek backward",
              "key": "shift+cmd+left"
            },
            {
              "title": "Seek forward",
              "key": "shift+cmd+right"
            },
            {
              "title": "Raise volume",
              "key": "cmd+up"
            },
            {
              "title": "Lower volume",
              "key": "cmd+down"
            }
          ]
        },
        {
          "title": "Navigation",
          "shortcuts": [
            {
              "title": "Home",
              "key": "shift+opt+h"
            },
            {
              "title": "Back in history",
              "key": "opt+left"
            },
            {
              "title": "Forward in history",
              "key": "opt+right"
            },
            {
              "title": "Preferences",
              "key": "cmd+,"
            },
            {
              "title": "Currently playing",
              "key": "shift+opt+j"
            },
            {
              "title": "Search",
              "comment": "Focuses the top search bar in Home",
              "key": "cmd+l"
            },
            {
              "title": "Liked songs",
              "key": "shift+opt+s"
            },
            {
              "title": "Queue",
              "key": "shift+opt+q"
            },
            {
              "title": "Your Library",
              "key": "shift+opt+0"
            },
            {
              "title": "Your playlists",
              "key": "shift+opt+1"
            },
            {
              "title": "Your podcasts",
              "key": "shift+opt+2"
            },
            {
              "title": "Your artists",
              "key": "shift+opt+3"
            },
            {
              "title": "Your albums",
              "key": "shift+opt+4"
            },
            {
              "title": "Your audiobooks",
              "key": "shift+opt+5"
            },
            {
              "title": "Made for you",
              "key": "shift+opt+m"
            },
            {
              "title": "New Releases",
              "key": "shift+opt+n"
            },
            {
              "title": "Charts",
              "key": "shift+opt+c"
            }
          ]
        },
        {
          "title": "Layout",
          "shortcuts": [
            {
              "title": "Toggle left sidebar",
              "key": "shift+opt+l"
            },
            {
              "title": "Decrease left sidebar width",
              "key": "shift+opt+left"
            },
            {
              "title": "Increase left sidebar width",
              "key": "shift+opt+right"
            },
            {
              "title": "Toggle right sidebar",
              "key": "shift+opt+r"
            },
            {
              "title": "Decrease right sidebar width",
              "key": "shift+opt+down"
            },
            {
              "title": "Increase right sidebar width",
              "key": "shift+opt+up"
            }
          ]
        },
        {
          "title": "Editing playlists",
          "shortcuts": [
            {
              "title": "Cut from playlist",
              "key": "cmd+x"
            },
            {
              "title": "Delete from playlist",
              "key": "backspace"
            },
            {
              "title": "Copy selected song",
              "key": "cmd+c"
            },
            {
              "title": "Paste selected song",
              "comment": "Pastes a link to the song in a text editor",
              "key": "cmd+v"
            }
          ]
        }
      ]
    }
  ]
}
